### ISSUE TITLE
Cannot add Kagi Search

### ISSUE THREAD

**Issue by fboundp** [MindMacApp/MindMac#4]
When attempting to add my API key, I get the following (truncated) error:

```
{"meta":{"id":"2a78303241c5cd8d359a098d6a818cd9", "node":"us-west2","ms":0,"api_balance":5.0},"data":null, "error": [{"code":2,"msg":"Unauthorized: the...
```

**Comment by hugo53** [comment]
@fboundp Your Kagi Search API key is unauthorized. Kagi Search API now is in closed beta and is currently available to Kagi Business (Team) plan. Please reach out to [support@kagi.com](mailto:support@kagi.com) for invite. You can check more at https://help.kagi.com/kagi/api/search.html

**Comment by fboundp** [comment]
Ah, thank you, I did not realize that limitation.
