### ISSUE TITLE
Can't add Anthropic Claude to MindMac

### ISSUE THREAD

**Issue by christopherflora** [MindMacApp/MindMac#8]
I’ve just signed up for an Anthropic Claude account and have generated a new API key.  Unfortunately, I can’t get MindMac to accept it.  

When I go to the “Create New API Endpoint” screen, I select “Anthropic Claude” as the provider in the drop-down, which populates “Anthropic Claude” in the Name field and “https://api.anthropic.com/v1/messages” in the URL field.  I then paste in my API Key as copied directly from the Anthropic Console.  When I hit save, I get a red message showing “model: claude-instant-1.2”, and nothing happens.  I can hit save over and over, but the screen stays there.  The only change is that, in place of the red “model” message, I very briefly see a loading statement “It may take some time to validate the API endpoint and key, please be patient”.  Here’s a screenshot:
<img width="612" alt="image" src="https://github.com/user-attachments/assets/45ef3b7c-2902-45ac-88dc-1162ab7ffdda">

Clicking the info button beside the red text gives a screen talking about issues with OpenAI API keys:
<img width="661" alt="image" src="https://github.com/user-attachments/assets/d48a41d5-4546-40f8-ae97-49ed3d73cc87">

I’m running the latest MindMac (1.9.22 build 91).
Any ideas on next steps here?  I've used this exact same API Key in an Obsidian plugin and in Bolt.ai with no issues.

**Comment by christopherflora** [comment]
I'm guessing this is because the claude-instant-1.2 model was deprecated on September 4, 2024?

https://docs.anthropic.com/en/docs/resources/model-deprecations
<img width="734" alt="image" src="https://github.com/user-attachments/assets/342f803c-a7dd-405e-b32d-fbbe79d25817">

**Comment by gmorain** [comment]
Same problem here... Just created an Anthropic account and not able to add this to MindMac. Any update on this issue?

@christopherflora Please confirm you have disabled or deleted the API key published in the image above ;-)

**Comment by christopherflora** [comment]
Thanks for the heads-up, and yes I've deleted that one.  
This issue is also flagged on the mindmac roadmap site here: https://mindmac.canny.io/feature-requests/p/bug-fix-you-cannot-add-anthropic-claude-to-mindmac
No comment on this issue from the developer there, either, but that site looks to be updated more regularly.  I'm keeping an eye on both platforms for now.

**Comment by michaelpmaley** [comment]
+1 
I emailed the support link last week, but have not heard back.

**Comment by rotemdoron** [comment]
same here getting the same error

**Comment by hugo53** [comment]
@christopherflora @gmorain @michaelpmaley @rotemdoron 

Hello everyone, thank you all for reporting the issue. I sincerely apologize for the delayed response.

This issue has been fixed since the version [1.9.23](https://github.com/MindMacApp/MindMac/releases/download/1.9.23/MindMac_1.9.23.dmg). Please upgrade on your end. 

Thank you all so much!

**Comment by dupreez** [comment]
The problem persists even with MindMac version 1.9.23, except that the red message says "model: claude-2.1". 

![Image](https://github.com/user-attachments/assets/95051abe-50c2-4126-bc5e-7d37b6831d3c)
